DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(
    ID BIGINT PRIMARY KEY auto_increment,
    NAME VARCHAR(127) NOT NULL
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
    ID BIGINT PRIMARY KEY auto_increment,
    FULLNAME VARCHAR(511) NOT NULL,
    ALIAS VARCHAR(127)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY auto_increment,
    NAME VARCHAR(255) NOT NULL,
    AUTHOR_ID BIGINT NULL,
    GENRE_ID BIGINT NULL
);

ALTER TABLE BOOKS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID);
ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID);
