spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect