localeDefault: ru-RU
spring:
  messages:
    basename: i18n/messages/messages
  redis:
    database: 1
server:
  port: 8083
nameQueueInOut: QueueInOut
bot:
  name: XXXmeIxBot
  token: 1924794338:AAHXnpOAft0PL5ova6vTshZZ9kv4GmWl-jA