version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    networks:
      - skynet
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
    hostname: redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
networks:
  skynet:
volumes:
  redis-data: