logging:
  file:
    path: "target/app.log"
    name: app.log
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
      show-details: always
    logfile:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "metrics,logfile,health"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true