CREATE TABLE GENRE(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(127) NOT NULL
);

CREATE TABLE AUTHOR(
    ID BIGINT PRIMARY KEY,
    FULLNAME VARCHAR(511) NOT NULL,
    ALIAS VARCHAR(127)
);

CREATE TABLE BOOK(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    AUTHOR_ID BIGINT REFERENCES AUTHOR(ID),
    GENRE_ID BIGINT REFERENCES GENRE(ID)
);

CREATE TABLE COMMENT(
    ID BIGINT PRIMARY KEY,
    DESCRIPTION VARCHAR(8191),
    BOOK_ID BIGINT REFERENCES BOOK(ID)
);